FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN pip install uv && \
    uv sync --system --no-cache --frozen-lock

COPY src/ ./src/
COPY models/model.joblib ./models/
COPY data/data.csv ./data/

EXPOSE 5000

CMD ["python", "-m", "gunicorn", "--bind", "0.0.0.0:5000", "src.app:app"]